### ISSUE TITLE
Usage of std::auto_ptr prevents compilation of consuming projects when using C++17

### ISSUE THREAD

**Issue by bwalden** [resiprocate/resiprocate#147]
As we know, C++17 removes std::auto_ptr. It looks like this is used in a few places throughout resiprocate.

I can see a couple of options to move forward:

1. Replace usages of std::auto_ptr with resip::SharedPtr.
2. Replace usages of std::auto_ptr with std::shared_ptr or std::unique_ptr as appropriate. This would make C++11 compiler support a requirement.

Both of the suggested options would mean a breaking change where std::auto_ptr is used publicly.

Any opinions or suggestions?

**Comment by dpocock** [comment]
At this point, I feel that option (1) is better because it will ensure consistency through the project.  Later, we could then change all SharedPtr to one of the newer pointers.

**Comment by gjasny** [comment]
Right now you can work-around by setting some defines (`_HAS_AUTO_PTR_ETC` for MSVC, `_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR` for libc++).

I'd vote against replacing the auto_ptrs with shared pointers for two reasons:
- You throw away life-cycle information. If you later convert to std::unique and std::shared pointers, you'll have to do some digging what the pointer type was before (and hope semantics did not change in between)
- You change life-cycle semantics and maybe introduce circular dependencies.

With the work-arounds to enable the auto_ptrs still available I'm thinking it's time to migrate the resiprocate code base to C++11 and start with replacing the auto_ptrs by std::unique_ptr and std::move.

**Comment by sgodin** [comment]
Great points Gregor, I agree.  I think it's time we made the leap to C++11
as well.  Is there anyone that is aware offhand that this will break things
in their environment?

Scott

**Comment by bwalden** [comment]
In light of this discussion and because I need this for a project I'm working on, I've implemented a change on my fork and submitted pull request #148 for review.

**Comment by sgodin** [comment]
If we decide to make the leap to C++ 11 I can't see a reason to keep around
our resip::SharedPtr, if we are doing an ABI break with std::unique we may
as well break resip::SharedPtr and change to std::shared_ptr.  Thoughts?

Scott

**Comment by gjasny** [comment]
Yes, I also think it should go away.

**Comment by portsip** [comment]
Totally agree use the std::shared_ptr and std::unique_ptr.
I also suggest use the std::condition_variable to replace the resip::Lock and resip::Condition in all resip FIFO, since in our product, we encounter the deadlock issue on windows, the details is here: https://list.resiprocate.org/archive/resiprocate-users/msg02818.html
The deadlock is disappeared after we used std::condition_variable.

Maybe we can go farther to use the std::mutex, std::shared_mutex std::unique_lock, std::shared_lock to replace the resip:mutex, resip::lock, resip:RWLock.

**Comment by portsip** [comment]
My OS is Debian 10.4(64bit), and GCC is GCC version 8.3.0.
I got the below error when I try to compile it with PR148 (no matter compile the master branch with same steps):

```
root@2b23c04b211e:/home/pp/3rd/resiprocate# autoreconf --install
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
configure.ac:23: installing 'build-aux/compile'
configure.ac:20: installing 'build-aux/config.guess'
configure.ac:20: installing 'build-aux/config.sub'
configure.ac:17: installing 'build-aux/install-sh'
configure.ac:17: installing 'build-aux/missing'
apps/clicktocall/Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
root@2b23c04b211e:/home/pp/3rd/resiprocate# ./configure --prefix=/usr/local --with-ssl --enable-ipv6   --enable-assert-syslog  --with-pic --enable-shared=no  CXXFLAGS="-I`pwd`/" CPPFLAGS="-DNDEBUG"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for a sed that does not truncate output... (cached) /bin/sed
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... (cached) ranlib
./configure: line 11874: gperf: command not found
./configure: line 11894: syntax error near unexpected token `11'
./configure: line 11894: `AX_CXX_COMPILE_STDCXX(11)'

```

**Comment by bwalden** [comment]
> My OS is Debian 10.4(64bit), and GCC is GCC version 8.3.0.
> I got the below error when I try to compile it with PR148 (no matter compile the master branch with same steps):
> 
> ```
> root@2b23c04b211e:/home/resiprocate# autoreconf --install
> libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
> libtoolize: copying file 'build-aux/ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
> libtoolize: copying file 'm4/libtool.m4'
> libtoolize: copying file 'm4/ltoptions.m4'
> libtoolize: copying file 'm4/ltsugar.m4'
> libtoolize: copying file 'm4/ltversion.m4'
> libtoolize: copying file 'm4/lt~obsolete.m4'
> libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
> configure.ac:23: installing 'build-aux/compile'
> configure.ac:20: installing 'build-aux/config.guess'
> configure.ac:20: installing 'build-aux/config.sub'
> configure.ac:17: installing 'build-aux/install-sh'
> configure.ac:17: installing 'build-aux/missing'
> apps/clicktocall/Makefile.am: installing 'build-aux/depcomp'
> parallel-tests: installing 'build-aux/test-driver'
> root@2b23c04b211e:/home/resiprocate# ./configure --prefix=/usr/local --with-ssl --enable-ipv6   --enable-assert-syslog  --with-pic --enable-shared=no  CXXFLAGS="-I`pwd`/" CPPFLAGS="-DNDEBUG"
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking how to create a pax tar archive... gnutar
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking whether make supports the include directive... yes (GNU style)
> checking dependency style of gcc... gcc3
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking how to print strings... printf
> checking for a sed that does not truncate output... /bin/sed
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for fgrep... /bin/grep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /bin/dd
> checking how to truncate binary pipes... /bin/dd bs=4096 count=1
> checking for mt... no
> checking if : is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... no
> checking whether to build static libraries... yes
> checking how to run the C++ preprocessor... g++ -E
> checking for ld used by g++... /usr/bin/ld -m elf_x86_64
> checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking for g++ option to produce PIC... -fPIC -DPIC
> checking if g++ PIC flag -fPIC -DPIC works... yes
> checking if g++ static flag -static works... yes
> checking if g++ supports -c -o file.o... yes
> checking if g++ supports -c -o file.o... (cached) yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... (cached) GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking for a sed that does not truncate output... (cached) /bin/sed
> checking whether make sets $(MAKE)... (cached) yes
> checking for ranlib... (cached) ranlib
> ./configure: line 11894: syntax error near unexpected token `11'
> ./configure: line 11894: `AX_CXX_COMPILE_STDCXX(11)'
> ```

Do you have autoconf-archive installed? You'll need that for AX_CXX_COMPILE_STDCXX.

**Comment by portsip** [comment]
> > ```
> 
> Do you have autoconf-archive installed? You'll need that for AX_CXX_COMPILE_STDCXX.

Thank you very much, yes, now I get it compiled after installed the autoconf-archive.
BR

**Comment by portsip** [comment]
If we use the resipfaststreams (comment out the RESIP_USE_STL_STREAMS in resipfaststreams .hxx), we will get below issue when compile it (Debian 10.4, 64bit, GCC 8.3):

```
/usr/include/c++/8/ostream:682:5: note:   template argument deduction/substitution failed:
/usr/include/c++/8/ostream: In substitution of 'template<class _Ostream, class _Tp> typename std::enable_if<std::__and_<std::__not_<std::is_lvalue_reference<_Tp> >, std::__is_convertible_to_basic_ostream<_Ostream>, std::__is_insertable<typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type, const _Tp&, void> >::value, typename std::__is_convertible_to_basic_ostream<_Tp>::__ostream_type>::type std::operator<<(_Ostream&&, const _Tp&) [with _Ostream = resip::ResipFastOStream&; _Tp = std::shared_ptr<resip::SipMessage>]':
DialogSet.cxx:305:16:   required from here
/usr/include/c++/8/ostream:682:5: error: no type named 'type' in 'struct std::enable_if<false, void>'
In file included from ../../rutil/Data.hxx:10,
```

**Comment by bwalden** [comment]
I think I've fixed this now.

resip::SharedPtr defined a stream insertion operator using EncodeStream. Which is define to be either std::ostream or resip::ResipFastOStream depending on the definition of RESIP_USE_STL_STREAMS.

Obviously std::shared_ptr defines a stream insertion operator using std::ostream, never resip::ResipFastOStream. My solution was to define a stream insertion operator for std::shared_ptr<T> using resip::ResipFastOStream in resipfaststreams.hxx.

I also noted that un-defining RESIP_USE_STL_STREAMS prevents reprolib from compiling.

`resiprocate\repro\AccountingCollector.cxx(644,36): error C2665: 'json::Writer::Write': none of the 7 overloads could convert all the argument types
resiprocate\contrib\cajun\include\cajun\json\writer.inl(45,21): message : could be 'void json::Writer::Write(const json::UnknownElement &,std::ostream &)'
resiprocate\contrib\cajun\include\cajun\json\writer.inl(51,21): message : or       'void json::Writer::Write(const json::Null &,std::ostream &)'
resiprocate\contrib\cajun\include\cajun\json\writer.inl(50,21): message : or       'void json::Writer::Write(const json::Boolean &,std::ostream &)'
resiprocate\contrib\cajun\include\cajun\json\writer.inl(48,21): message : or       'void json::Writer::Write(const json::Number &,std::ostream &)'
resiprocate\contrib\cajun\include\cajun\json\writer.inl(49,21): message : or       'void json::Writer::Write(const json::String &,std::ostream &)'
resiprocate\contrib\cajun\include\cajun\json\writer.inl(47,21): message : or       'void json::Writer::Write(const json::Array &,std::ostream &)'
resiprocate\contrib\cajun\include\cajun\json\writer.inl(46,21): message : or       'void json::Writer::Write(const json::Object &,std::ostream &)'
resiprocate\repro\AccountingCollector.cxx(644,36): message : while trying to match the argument list '(json::Object, resip::DataStream)'`

This seems to rely on resip::DataStream inheriting from std::ostream. Is this experienced by anyone else?

**Comment by bwalden** [comment]
PR #148 has now been merged.
