### ISSUE TITLE
link error undefined reference to `resip::DayOfWeekHash::in_word_set(char const*, unsigned int)

### ISSUE THREAD

**Issue by zhangkai1234** [resiprocate/resiprocate#156]
windows link success,but link error on center os platform.

/build/lib/libresip.a(DateCategory.o): In function `resip::DateCategory::DayOfWeekFromData(resip::Data const&)':
/mnt/resiprocate/resip/stack/DateCategory.cxx:199: undefined reference to `resip::DayOfWeekHash::in_word_set(char const*, unsigned int)'
./build/lib/libresip.a(DateCategory.o): In function `resip::DateCategory::MonthFromData(resip::Data const&)':
/mnt/resiprocate/resip/stack/DateCategory.cxx:216: undefined reference to `resip::MonthHash::in_word_set(char const*, unsigned int)'
./build/lib/libresip.a(DateCategory.o): In function `resip::DateCategory::DayOfWeekFromData(resip::Data const&)':
/mnt/resiprocate/resip/stack/DateCategory.cxx:199: undefined reference to `resip::DayOfWeekHash::in_word_set(char const*, unsigned int)'
./build/lib/libresip.a(DateCategory.o): In function `resip::DateCategory::MonthFromData(resip::Data const&)':
/mnt/resiprocate/resip/stack/DateCategory.cxx:216: undefined reference to `resip::MonthHash::in_word_set(char const*, unsigned int)'
./build/lib/libresip.a(Headers.o): In function `resip::Headers::getType(char const*, int)':
/mnt/resiprocate/resip/stack/Headers.cxx:350: undefined reference to `resip::HeaderHash::in_word_set(char const*, unsigned int)'
./build/lib/libresip.a(MethodTypes.o): In function `getMethodType':
/mnt/resiprocate/resip/stack/MethodTypes.cxx:62: undefined reference to `resip::MethodHash::in_word_set(char const*, unsigned int)'
./build/lib/libresip.a(MethodTypes.o): In function `resip::getMethodType(char const*, int)':
/mnt/resiprocate/resip/stack/MethodTypes.cxx:62: undefined reference to `resip::MethodHash::in_word_set(char const*, unsigned int)'
collect2: error: ld returned 1 exit statu

**Comment by sgodin** [comment]
There are a few older posts on this topic - try searching the mailing
lists.

Scott

**Comment by fklassen** [comment]
Try running `gperf_w32.bat` to regenerate these source file.

I had similar issues on Apple with Xcode 12 beta 4 which uses an older gperf 3.0.3. The above files were generated with gperf 3.1.

    Undefined symbols for architecture x86_64:
    "resip::HeaderHash::in_word_set(char const*, unsigned int)", referenced from:
        import-atom in libresip.dylib
    "resip::MethodHash::in_word_set(char const*, unsigned int)", referenced from:
        import-atom in libresip.dylib
    "resip::DayOfWeekHash::in_word_set(char const*, unsigned int)", referenced from:
        import-atom in libresip.dylib
    "resip::ParameterHash::in_word_set(char const*, unsigned int)", referenced from:
        import-atom in libresip.dylib
    "resip::MonthHash::in_word_set(char const*, unsigned int)", referenced from:
        import-atom in libresip.dylib

I had to manually generate the files since there is no UNIX style script to do so.

Question: Should this files be generated automatically at compile time?

**Comment by sgodin** [comment]
Windows should be fine with the files generated in the GIT repo.  The
problem happens on linux only as far as I know.  I believe the previous
suggestion was to "touch" each gperf file to get the scripts to regen them,
and to make sure you have the correct the gperf version installed (3.1 I
believe - from memory).

Scott

**Comment by tangm421** [comment]
我也遇到了，很奇怪，我看到文件夹 resip/stack/gen 下也生成hash文件了，而且构建的.a库中解压出的.o文件中也能找到对应的静态文本，但是链接的时候还是会报这个错误。
按照下面的方法，我删除了文件夹 resip/stack/gen 下所有的.cxx文件，然后重新make就没这个链接问题了。
> https://list.resiprocate.org/archive/resiprocate-devel/msg01090.html

**Comment by gkorovkin** [comment]
For macos:
1. Delete all gperf auto generated files
2. Run autoreconf before configure invocation
