### ISSUE TITLE
can't compile with Visual Studio - MSB8036

### ISSUE THREAD

**Issue by seppy87** [resiprocate/resiprocate#159]
Hallo I am trying to compile rutil but I can't retarget it. Retargeting Project has no effect.

It still wants the old SDK
Greetings

**Comment by sgodin** [comment]
I have no trouble retargeting the main resiprocate solution to other SDK
versions using VS2017.  What Visual Studio version are you using?  Also,
are you using resip from git mainline or some release of the code?

Thanks,
Scott
