### ISSUE TITLE
operator= in MultipartMixedContents makes an empty copy

### ISSUE THREAD

**Issue by cyr2242** [resiprocate/resiprocate#162]
The MultipartMixedContents::operator= method iterates over its own mContents vector as the source vector for cloning instead rhs's one and resulting in an empty MultipartMixedContents destination object.

MultipartMixedContents&
MultipartMixedContents::operator=(const MultipartMixedContents& rhs)
{
   if (this != &rhs)
   {
      Contents::operator=(rhs);
      clear();
      
      for (vector<Contents*>::iterator i = mContents.begin(); 
           i != mContents.end(); ++i)
      {
         mContents.push_back( (*i)->clone() );
      }
   }
   return *this;
}

**Comment by sgodin** [comment]
Thank you for reporting this!  I have fixed this in Git master, and added a
test to testMultipartMixedContexts.cxx.

Scott
