### ISSUE TITLE
Repro Monkey/Baboon/Lemur pipe interleaving

### ISSUE THREAD

**Issue by IvanRibakov** [resiprocate/resiprocate#167]
Hi, I'm currently evaluating resip/repro as a foundation for the custom SIP routing proxy. I've been studying [repro overview document](https://www.resiprocate.org/images/f/f0/Repro_1.8_Overview.pdf) to get a better idea about what comes out of the box with repro and I have a question related to the "Monkey/Baboon/Lemur" concepts:

![image](https://user-images.githubusercontent.com/3639958/103534345-fa80ce00-4e8e-11eb-8ab3-6eb3655bd209.png)

I understand that sequential forking can be achieved using `QValueTargetHandler`.

**My question is:** 

 - can "Monkey", "Baboon" and "Lemur" pipe execution interleave? 

The reason I'm asking this question is because I need to be able to implement a routing logic where next target may depend on the previous target response (think of a conditional fallback routing). To implement this using concepts from the above diagram, I imagine I would need to:

- first execute a Monkey that produces "target 1"
- then execute some of the Baboons to prepare/eject the request to the "target 1"
- then execute a Lemur to process the response
- then (optionally) repeat the Monkey/Baboon/Lemur cycle for the next target dynamically based on the "target 1" response until the call is connect (or max number of attempts is reached)

**Comment by sgodin** [comment]
Hi Ivan,

The processors above are created and installed into processor chains when
you bootstrap your proxy, then requests/responses flow through them when
they arrive.  So you don't need to "execute" a processor, and they
"interleave" naturally.  Here's an example flow:


   1. Request arrives at proxy.  The request traverses the installed Monkey
   chain, collecting Targets as it goes.  Note:  Monkey's can also reject or
   challenge a request as well (in which case the chain is terminated).
   2. The request and Target list collect from 1, now traverse the Baboons,
   and 1 or more requests are sent out on the wire (ie: forking).  Baboons can
   control the timing and logic of the forking (see QValueTargetHandler).
   3. A single response, or multiple responses will arrive (ie: if forking
   occurred).  And each one will flow through the chain of Lemurs.  If all
   active transactions have completed  then the Baboons are triggered and they
   may send out another request (ie: serial forking).  See the logic in the
   QValueTargetHandler and RequestContext::doPostResponseProcessing.

I think you will find that you can accomplish all the custom routing logic
your application will need.

Best Regards,
Scott Godin
