### ISSUE TITLE
setServerAuthManager can not  effect for different uac(sip client) clients

### ISSUE THREAD

**Issue by ChuLiqiang** [resiprocate/resiprocate#170]
We want my uas(sip server) have different registered behavior for some especially uac(sip client).
For example:
(1) No authenticate
    (a)uac A register to uas,
    (b)uas response uac sip 200 ok.
(2)authenticate
     (a)uac B register to uas
     (b)uas response uac sip 401 Unauthorized
     (c)uac response uas register to authenticate
     (d)uas response uac sip 200 ok

We want uas can support (1)(2) behavior  at same times.but when we call setServerAuthManager,All register will used (2) behavior.All  register will used (1) behavior when not call setServerAuthManager.
How can tell me,How can i do？please....

**Comment by sgodin** [comment]
The repro proxy is a good example of how to do this.  rePro will NOT
challenge requests that are received from IP addresses in its ACL list.
You can override the ServerAuthManager and make your own decisions on which
requests to require authentication for.
See ReproServerAuthManager::requiresChallenge for an example.

Scott
