### ISSUE TITLE
WebSocket handshake failure in WSS transport

### ISSUE THREAD

**Issue by krishnaplivo** [resiprocate/resiprocate#173]
I was trying to use reSIProcate as a SIP client on an iOS device. I m able to compile it for iOS arch and make SIP registrations and call using TLS, but I wanted to use SIP over WebSockets for registration. 

However, while testing the same I am facing an issue with the WebSocket handshake. I wanted to check whether the SIP over WebSockets is supported for reSIProcate clients or is it just limited to the repro server?

Currently, I m getting this error in logs :

STACK | 20210127-190252.428 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/ssl/TlsConnection.cxx:483 | SSL bytesRead=615
ERR | 20210127-190252.428 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/ConnectionBase.cxx:645 | demo--> connection base [ V4 10.20.30.40:5063 WSS targetDomain=org.demo.com flowKey=25 transportKey=1 ] | 0x0 | 0x0
ERR | 20210127-190252.429 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/ConnectionBase.cxx:796 | No SecWebSocketKey header
ERR | 20210127-190252.429 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/ConnectionBase.cxx:712 | Failed to parse WebSocket initialization request
DEBUG | 20210127-190252.429 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/Connection.cxx:433 | Closing connection bytesRead=-1
DEBUG | 20210127-190252.429 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/ConnectionManager.cxx:217 | ConnectionManager::removeConnection()
DEBUG | 20210127-190252.429 |  | RESIP:TRANSPORT | 0x700007414000 | /Users/demo/demo-resip/resiprocate/resip/stack/ConnectionBase.cxx:115 | ConnectionBase::~ConnectionBase 0x7fc93f611d10
INFO | 20210127-190252.429 |  | RESIP:TRANSACTION | 0x700007391000 | /Users/demo/demo-resip/resiprocate/resip/stack/TuSelector.cxx:102 | Sending ConnectionTerminated [ V4 10.20.30.40:5063 WSS targetDomain=org.demo.com flowKey=25 transportKey=1 ] to TUs
DEBUG | 20210127-190252.466 |  | RESIP:DUM | 0x70000751a000 | /Users/demo/demo-resip/resiprocate/resip/dum/DialogUsageManager.cxx:1477 | connection terminated message

**Comment by sgodin** [comment]
I'm not aware of any issues using client side WSS transports, that being
said, most (if not all) of my own personal uses have been server side
connections with repro.

Scott

**Comment by sgodin** [comment]
Yes websockets are supported for the resiprocate stack, both client and server connections.  I'll leave this issue for a bit longer, if you can please add more details.  A pcap trace perhaps.
