### ISSUE TITLE
ConversationManager::muteMicrophone does not restore microphone volume level

### ISSUE THREAD

**Issue by simone-gaiarin** [resiprocate/resiprocate#174]
In Windows 10 after disabling and re-enabling the microphone the microphone volume is not restored to the original level. This can be verified in Windows by looking at the volume bar in Sound Settings > Input > Device porperties > Volume; after unmuting the volume level is set to 7.

```
ConversationManager::muteMicrophone(true);
ConversationManager::muteMicrophone(false);
```

resiprocate: 1.12 
sipXtapi: repo: sipXtapi-svn-mirror@e8e4ad0
OS: Windows 10 Pro build 19042

**Comment by sgodin** [comment]
Hi Simone,

recon uses the sipXtapi project for media processing and the mute call is
made on the sipXtapi API's.  I would suggest cross posting this to the
sipXtapi mailing list as well, since it's a comment that is more applicable
to the code in that project.

http://sipxwiki.sipez.com/wiki/SipXtapi

Scott

**Comment by simone-gaiarin** [comment]
I wanted to but on that website, there are multiple links to different mailing lists and none is working. Do you know an updated link to an active mailing list?

**Comment by sgodin** [comment]
I realize there is very little traffic on the mailing list, but I would try posting there regardless. I believe the project maintainer, Dan Petrie, still monitors it.

Scott

**Comment by simone-gaiarin** [comment]
Now I've found the correct mailing list.

I have cross posted the issue here:
https://groups.google.com/g/sipx/c/W7iGfHqms-w

**Comment by simone-gaiarin** [comment]
Sorry, forgot to reply for a while.

According to the reply of Dan, it is best to mute the microphone by setting the gain to zero, he proposed this code:
if(mute){
    mMediaInterface->getInterface()->setMicGain(0.0);
} else {
   // Note if you have changed the mic mix weights else where in the
   // conversation manager, then you    
   // will need to cache that non-default mix weight and use that instead of 1.0   
mMediaInterface->getInterface()->setMicGain(1.0);
}

though one problem left is to get the original mic gain before altering it.
In conversation manager there seems no way to get the mic gain, is it right?

**Comment by sgodin** [comment]
Hi Simone,

Looking at the sipX code muteMicrophone does just call the same api as
setMicrophoneGain, it is here:
OsStatus sipXmediaFactoryImpl::muteMicrophone(UtlBoolean bMute)
{
   if (bMute)
   {
      MpCodec_setGain(0);
   }
   else
   {
      MpCodec_setGain(miGain);
   }
   return OS_SUCCESS;
}

When you unmute it unmutes to the stored level (miGain) from the last time
setMicrophoneGain was called.  So if you call setMicGain when you app
starts, then mute/unmute will work as you expected.

Querying the gain when you application starts is not currently available
through recon, but it would be an easy API to add, as it looks like sipX
offers this call:
sipXmediaFactoryImpl::getMicrophoneGain.  We would gladly accept a pull
request for this.  :)

Best Regards,
Scott
