### ISSUE TITLE
Link static library error when i add a member method in DialogUsage class

### ISSUE THREAD

**Issue by mar348** [resiprocate/resiprocate#179]
Hello,

  When i add a member method "void setLocalContact(const NameAddr& contact);" in DialogUsage class, and i build the library successfully but linking failed:
  undefined reference to `resip::DialogUsage::setLocalContact(resip::NameAddr const&)'

please help me and thanks.

DialogUsage.hxx
`void setLocalContact(const NameAddr& contact);`

DialogUsage.cxx:
`void DialogUsage::setLocalContact(const NameAddr& contact) {
	mDialog.mLocalContact = contact;
}`

**Comment by sgodin** [comment]
This sounds like more of a general programming / compiling / linking question that is off topic for this list.  Make sure you are linking with the correct library.
Scott
