### ISSUE TITLE
Resip memory increase but never decrease

### ISSUE THREAD

**Issue by r1a2y3** [resiprocate/resiprocate#180]
Hi , I build a server using resip-1.10.2 as a  sip redirect server to provide load balance. The memory will increase when received more INVITE request. Much worse is that if our server runs a bit slowly, more and more INVITE received in resip is handled slowly. This cause memory increases and the memory will not decrease any more even if there is no new call later. The worstest case is our server occupy 100G memory and is killed the the operation system.

Hope I have describe the question clearly.  Could you please help me to figure the root cause of the memory increasing? Is there has a buffer?

**Comment by sgodin** [comment]
Are you using repro as is, or your own application based on resip?  There
are many reasons memory could go up and not go down, including a leak in
your application logic.  If you are using dum you need to make sure all
usages are cleaned up properly.  I don't know of any leaks in the repro
proxy project or any projects I've worked on based on DUM.  I would
suggest you use a leak detection tool to identify which objects are not
going away, then try to focus on what might cause it.

Scott

**Comment by sgodin** [comment]
Closing this issue as no further information was provided.
