### ISSUE TITLE
Need advice on qop and useAuthInt()

### ISSUE THREAD

**Issue by pbalash0v** [resiprocate/resiprocate#182]
Hello everyone !
Need advices on proper usage of ServerAuthManager.

1. In  [22.4 The Digest Authentication Scheme](https://datatracker.ietf.org/doc/html/rfc3261#section-22.4) there is a point 8:
```
However, servers MUST always send a "qop" parameter in WWW-Authenticate and Proxy-Authenticate header field values.
```
 As of my understanding the base implementation of ServerAuthManager's useAuthInt() returns false by default, which leads to no qop parameter in digest header of response at all. Is there some supposed usage, which conforms to RFC, but still doesn't include qop parameter (i.e. doesn't override base's useAuthInt() to return true) ?
 
2. Closely related to (1). As I understand RFC considers legitimate options for qop to be in a form of `qop="auth,auth-int"` or `qop="auth"` or `qop="auth-int"`. Would you please suggest if there is a way to somehow realize this kinds scenarios with some methods of ServerAuthManager ? For me it looks like I can get `qop="auth,auth-int"` or no qop at all (see point 1 above).

Thanks for attention and all hard work on this project.

**Comment by sgodin** [comment]
Hi Pavel,

Just read through this and I agree we should be adding a qop parameter.  We
will need to ensure that resip can still receive a Digest response without
a qop parameter to ensure continued RFC2543 backwards compatibility.

We will have to track this as a TODO item for resip, and would gladly
accept any well tested pull requests from the community.

Best Regards,
Scott

**Comment by pbalash0v** [comment]
Hi Scott, thanks a lot for a prompt reply.

As of my second question - would you kindly please clarify - so there is no way to select which `qop` options be offered in header - it is only `qop="auth,auth-int"` that I can get being sent through ServerAuthManager API usage ?

To clarify a bit - I observe aforementioned behavior if I derive from ServerAuthManager and override useAuthInt() like:
```c++
bool useAuthInt() const override { return true; };
```
But what I'm looking is a way to get `qop` param look like this `qop="auth"` via reSIP API.

Thanks.
Regards,
Pavel

**Comment by sgodin** [comment]
You are correct if you disable authInt in resip, you do not get a qop
header.  There is no current way to get qop="auth" without making code
changes to resip.

Scott

**Comment by pbalash0v** [comment]
Scott, thanks a lot for a clarification.

Regards,
Pavel.
