### ISSUE TITLE
compile errors with c++17

### ISSUE THREAD

**Issue by kkseven** [resiprocate/resiprocate#184]
I use reSiprocate 1.12.0 with c++17,  and compilation failed with lots of errors , i.e. :
**no template named 'auto_ptr' in namespace 'std'**

I notice that the 1.13.0 is coming soon, so the temporary solution is that i checkout the master instead of 1.12.0.

my question is:
What is the day do 1.13.0 version to release?
Or can i use the master version to our release version?

**Comment by gjasny** [comment]
In all STL implementations I know youcould make the auto_ptr visible, again. You just need to globally set the proper define.

**Comment by kkseven** [comment]
> In all STL implementations I know youcould make the auto_ptr visible, again. You just need to globally set the proper define.

em...this suggestion is the first time i have ever heard.

my compilation environment is android with ndk 22.0.7026061, and camke config in build.gradle is as below:
cmake {
    abiFilters  "armeabi-v7a"
    cppFlags "-std=c++17 -fexceptions -frtti"
    arguments "-DANDROID_STL=c++_static",
            "-DANDROID_TOOLCHAIN=clang",
            "-DANDROID_PLATFORM=android-18",
            "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"
}

i'll post my result later.

**Comment by gjasny** [comment]
We're using something like this:
```cmake
if(ANDROID OR APPLE)
  target_compile_options(foo PUBLIC "-D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR")
endif()

if(WIN32)
  target_compile_options(foo PUBLIC "-D_HAS_AUTO_PTR_ETC")
endif()
```

**Comment by kkseven** [comment]
> We're using something like this:
> 
> ```cmake
> if(ANDROID OR APPLE)
>   target_compile_options(foo PUBLIC "-D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR")
> endif()
> 
> if(WIN32)
>   target_compile_options(foo PUBLIC "-D_HAS_AUTO_PTR_ETC")
> endif()
> ```

Thanks for your suggestion. Actually, i didn't try this. 
What I do is set the cppFlag from '-std=c++17' to '-std=c++14', and the problem was gone. 
I think this would be the simplest way to solve it. :-)
