### ISSUE TITLE
Multithreading calling dum - > makepagemessage() - > handlemanager: creating mhandlemap will be unsafe and memory exceptions will occur

### ISSUE THREAD

**Issue by Qingshan-github** [resiprocate/resiprocate#195]

**Comment by sgodin** [comment]
DUM is not thread safe.  Please see the following page for guidance:
https://www.resiprocate.org/DUM_Threading

I have highlighted a statement from the link above that applies to your specific issue:

Some DUM classes, notedly InviteSession, provide methods to post DumCommands to the dum process loop (eg. provideOfferCommand). Your application can use them to call DUM methods from another thread. Make sure though, that no other thread unsafe method is called **(eg. makeXXXX methods are not thread safe)**. If you need to call some of these methods, you must create your own commands.
