### ISSUE TITLE
https://github.com/resiprocate/resiprocate/wiki/Using-testUA broken

### ISSUE THREAD

**Issue by TheQue42** [resiprocate/resiprocate#203]
Hi,

Trying to wrap my head around all the components of reSIProcate, and looking especially at recon and reconserver. But the above link, results in:

 The wiki page took too long to render.
This wiki page’s content is too large to render on this page.

**Comment by sgodin** [comment]
Odd that page works fine for me.  Is anyone else seeing this issue?

Scott

**Comment by TheQue42** [comment]
What the.... I tried several times, and even with edge och chrome I think...NOW, it works for me too! Firefox did update this weekend, but I suspect Pebcac :-/
