### ISSUE TITLE
TLS deprecated versions

### ISSUE THREAD

**Issue by giulio-biondo** [resiprocate/resiprocate#213]
Is it possible to disable deprecated TLS versions (1.0 and 1.1)?

**Comment by dpocock** [comment]
To clarify: you want to prohibit reSIProcate accepting connections with those versions?

Is this specifically for repro (the proxy) or all the stack?

Please note that if you are using Linux then the OpenSSL package will disable the versions of SSL and TLS that are considered insecure and we don't need to make specific changes in reSIProcate.  If you want to implement a policy that is more strict than the OpenSSL package then we could support those configuration options in reSIProcate too

We already have OpenSSLCipherList in repro.config - we could try to permit similar granularity for TLS versions, within the abilities of the OpenSSL library.

**Comment by giulio-biondo** [comment]
I'm using DUM, so it would be great to be able to configure this on stack initialization
