### ISSUE TITLE
repro: registered account call fail

### ISSUE THREAD

**Issue by jimying** [resiprocate/resiprocate#214]
Two accounts registered to repro,   one call other, faild with 480 Temporarily Unavailable

accounts info：
|AOR | Contact | User Agent | Instance ID | Reg ID | QValue | Path | Sync'd? | Expires In |  
|-- | -- | -- | -- | -- | -- | -- | -- | -- | --|
|sip:5901@192.168.50.169 | sip:5901@192.168.50.169:25090;transport=udp | sip mock |   | 0 | 1 |   | false | 254s |  
|sip:5908@192.168.50.169 | sip:5908@192.168.50.168:35090;ob | MicroSIP/3.20.7 |   | 0 | 1 |   | false | 259s |  

I use default sample repro.config,  maybe need modify configure？？

PS
ip phone's "Instance ID"  is  NULL,    i test use the linphone ,which instanceId is not null,  can call other account

**Comment by sgodin** [comment]
The instance id should not be a factor here.  Does the URI in the request URI in the INVITE exactly match the registered AOR?  Make sure it doesn't contain the port.  Looking at the repro logs should help understand what is happening.

**Comment by jimying** [comment]
> The instance id should not be a factor here. Does the URI in the request URI in the INVITE exactly match the registered AOR?  Make sure it doesn't contain the port.  Looking at the repro logs should help understand what is happening.

you are right, log as follow
```
INFO | 20220211-122858.097 | repro | REPRO:APP | 140695501850368 | RequestContext.cxx:717 | numtrans=1 final=0 req=SipReq:  INVITE 5901@192.168.50.169:25060 tid=Pj2e2297cbf27d4d4783820a2f3864ba40 cseq=12401 INVITE contact=5908@192.168.50.168:35090 / 12401 from(wire)    : no targets for sip:5901@192.168.50.169:25060 send 480
```

MicroSIP sip client, use [pjsip](https://pjsip.org/) sip stack,  which INVITE request line contains the port ,   Maybe repro
should compatible with it

**Comment by sgodin** [comment]
repro is compliant to the RFC's in this manner.  I'm reasonably confident that it is possible to configure microsip / pjsip to not use the port on request uri's when calling.   I don't have it installed to check, but some combination of settings for SIP Server/SIP Proxy will likely get it working for you.  Try putting just the IP in the SIP Server setting (I suspect this is what forms the request uri's for outbound calls), and put IP:port into the SIP Proxy field.
