### ISSUE TITLE
Trickle ICE support

### ISSUE THREAD

**Issue by pbalash0v** [resiprocate/resiprocate#231]
Hello,

Looking through codebase I've got the impression that usage of Trickle ICE in SIP (as in RFC8840) is not implemented in reSIProcate at the moment. Would someone kindly confirm that ?

If this is the case than it seems that in order to add support one should implement a class for MIME of application/trickle-ice-sdpfrag, akin to DtmfPayloadContents.hxx, SdpContents.hxx etc. Anything else I completely miss that should be done ?

Thanks.
Regards,
Pavel.

**Comment by sgodin** [comment]
I haven't read RFC8840 in detail to be able to answer this definitively but
here are some points that may help:

   - reSIProcate does NOT have a specific Contents class that matches
   application/trickle-ice-sdpfrag at the moment
   - reSIProcate does have  a SdpContents class that you may be able to
   use, as long as there are not mandatory attributes in standard SDP that
   don't exist in tickle-ice-sdpfrag.  You may be able to use this and just
   manually change the content type header to be trickle-ice-sdpfrag
   - reSIProcate does have an OctetContents contents type, that can be used
   to build any text based body you like, then you can manually tweak the
   ContentType.  You will need to manually parse inbound message body string
   blobs.
   - It's not very difficult to add a new Contents class, if you want to go
   the route of adding the support in an ideal way.  We would gladly accept a
   pull request with this support.  :)

In general, and in the future,  it would be better to post queries like
this to GitHub discussion as opposed to issues:
https://github.com/resiprocate/resiprocate/discussions.

Best Regards,
Scott

**Comment by pbalash0v** [comment]
Scott, thanks a lot for such a thorough and prompt reply. My mistake in posting to issues. I've found out the existance of discussions only after I've posted here.

**Comment by dpocock** [comment]
You can see another example by looking at how I added MediaControlContents
https://github.com/resiprocate/resiprocate/commits/b3943ce9ed412e2302121f6cc766125a7746edc1/resip/stack/MediaControlContents.hxx
