### ISSUE TITLE
Mute on USB Microphone

### ISSUE THREAD

**Issue by andrea-ziggiotto** [resiprocate/resiprocate#233]
Hi,

Using the **sipxTapiConversationManager**, I've seen that the **muteMicrophone** function in windows works only with the jack microphone and not with the USB microphone.

In the logs of resiprocate, there is no trace of errors.

**Comment by sgodin** [comment]
Hi Andrea,

This issue is with the sipXtapi opensource project, although resip/recon uses this library, support for the library itself should come from that project. I would recommend posting this to their new GitHub repo issues list.

https://github.com/sipXtapi/sipXtapi/issues

Scott
