### ISSUE TITLE
Using Resip alongside boost asio

### ISSUE THREAD

**Issue by aerlfredith** [resiprocate/resiprocate#235]
I'm trying to build a project with both resip and boost included.
I ran into a class that wants to use both objects based on resip code using its asio copy and boost asio code.
This causes multiple declaration errors.

How should I best get around this problem. 
- replace resips asio dependency with an actual boost dependency ?
- rename resips asio namespace to be resip specific ?
- compiler black magic I'm not aware of ? (I'm using Visual Studio 2022 community edition)

**Comment by aerlfredith** [comment]
To be more specific, I am using a vcpkg installation of boost asio.
In the file asio/execution/set_done.hpp there are using statements and declarations in the asio_execution_set_done_fn namespace that conflict when included in the same file.

**Comment by sgodin** [comment]
resip uses the standalone asio library.  Standalone asio and boost::asio are already in different namespaces to solve these problems (ie: asio::execution vs boost::asio::execution).  Unfortunately it looks like asio didn't put namespace asio_execution_set_done_fn in different parent namespaces.  This sems like an oversight on their part.   I'm not sure offhand what would be the best/easiest solution.  

Converting resip to using boost::asio will likely solve your problem, but doing so brings in the requirement to link with a few boost libraries and doesn't allow full header-only mode for asio use.  I wasn't happy with that for inclusion in the resip repro, back when brining boost into a windows project was more of a pain than it is today.  Now that's it's much easier with Nuget (or vcpkg) we could re-evaluate that in the future.

Note:  The core stack, dum and repro don't use asio, so if you are only using these projects then you should also be fine.

Scott

**Comment by aerlfredith** [comment]
I added a pull request which gets around the problem without introducing the boost dependency.

**Comment by sgodin** [comment]
We currently bring in the asio headers from the source repo without any
modifications.  Thanks for the contribution, however, managing
customizations to the asio headers is likely not something we want to start
doing.

Scott

**Comment by jwhitworth-vicon** [comment]
For anyone else who finds this by searching for `asio_execution_set_done_fn`, it looks like this was fixed in Boost 1.77 bytrenaming the boost version of the namespace from `asio_execution_set_done_fn` to `boost_asio_execution_set_done_fn`.

**Comment by sgodin** [comment]
Great to know - thanks for that info!
