### ISSUE TITLE
question about CRLF keep-alive message

### ISSUE THREAD

**Issue by ww95211** [resiprocate/resiprocate#245]
Hi @sgodin , hope you all well! Recently I encountered a problem about Keep-Alive message in resiprocate  library. My testing scenario  is that I send a lot of CRLFs( single or double one time) in very short time after I connect to server TCP 5060 or TLS 5061 port,  the memory usage will be increased very high in short time. In my production, the same behavior is observed. Our server  should be attacked. I double checked source node,  I notice in ConnectionBase, the stack will new a SipMessage to handle these characters not just new KeepAlive or KeepAlivePong in this case. It will cause the size of mBufferList in SipMessage will be very huge. It will consume a lot of memories.  It is not expected. Any advice to add some protection? Thanks in advance!

**Comment by sgodin** [comment]
For outbound KeepAlives I don't see mBufferList being used at all.  And for
inbound Keepalives, I don't believe a SipMessage is even created when
receiving.   See code in ConnectionBase.cxx - preparseNewBytes.

But in general a rogue endpoint could exhaust your server memory in many
different ways.  I would recommend that you implement some kind of
blacklist logic for endpoints that "abuse" the server, ie: kill the TCP
connection and don't accept new ones or drop the UDP packets, from
blacklisted IP addresses/ports.  Unfortunately there is nothing built into
the stack at the moment to do that, so you will need to build it as custom
logic.

Scott

**Comment by sgodin** [comment]
Also, please use GitHub discussions to ask questions, and reserve "Issues" for proven/known issues.
