### ISSUE TITLE
Not find contact uisng LocationServer

### ISSUE THREAD

**Issue by blackStar1314** [resiprocate/resiprocate#259]
Firstly:
register 01 and 02
=== 01 ===
REGISTER sip:192.168.1.101:5061 SIP/2.0

Via: SIP/2.0/UDP 192.168.1.101:49233;rport=49233;branch=z9hG4bKPj864d09fa98314104a5c6d149c918c0fb

Max-Forwards: 70

Contact: <sip:01@192.168.1.101:49233;ob>

To: <sip:01@192.168.1.101>

From: <sip:01@192.168.1.101>;tag=276256159b5543fd8a64bf317c5c6f93

Call-ID: 540f10ef5ae3417a9cd4acf87bd8813f

CSeq: 40163 REGISTER

Expires: 300

Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS

User-Agent: MicroSIP/3.21.2

Content-Length: 0

=== 02 ===
REGISTER sip:192.168.1.101:5061 SIP/2.0

Via: SIP/2.0/UDP 192.168.1.103:1315;rport=1315;branch=z9hG4bKPj15737c9b917543e68ee481bb1c3b1299

Max-Forwards: 70

Contact: <sip:02@192.168.1.103:1315;ob>

To: <sip:02@192.168.1.101>

From: <sip:02@192.168.1.101>;tag=824c6e298a3e4dd4823d4a902c360256

Call-ID: 4deb1d579a534466a174f49d0aa9a55a

CSeq: 54601 REGISTER

Expires: 300

Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS

User-Agent: MicroSIP/3.20.7

Content-Length: 1

----------------------------------------------------------------------
Secondly, 01 call 02 by Location Server
=== 01  request ===

INVITE sip:01@192.168.1.101:5061 SIP/2.0

Via: SIP/2.0/UDP 192.168.1.103:1315;rport=1315;branch=z9hG4bKPj7e071925b87745c199f45a33449a2d04

Max-Forwards: 70

Contact: <sip:02@192.168.1.103:1315;ob>

To: <sip:01@192.168.1.101>

From: <sip:02@192.168.1.101>;tag=f2d996f8acfe4c7da56de9055d36a016

Call-ID: 163b8d8eda534056be8cef736be70928

CSeq: 19155 INVITE

Session-Expires: 1800

Min-SE: 90

Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS

Content-Type: application/sdp

Supported: replaces, 100rel, timer, norefersub

User-Agent: MicroSIP/3.20.7

Content-Length: 343

[SDP Description]

=== proxy response ===

SIP/2.0 480 Temporarily Unavailable

Via: SIP/2.0/UDP 192.168.1.103:1315;rport=1315;branch=z9hG4bKPj7e071925b87745c199f45a33449a2d04

To: <sip:01@192.168.1.101>;tag=fd174e1d

From: <sip:02@192.168.1.101>;tag=f2d996f8acfe4c7da56de9055d36a016

Call-ID: 163b8d8eda534056be8cef736be70928

CSeq: 19155 INVITE

Content-Length: 0

=== key codes ===
![image](https://user-images.githubusercontent.com/53989046/185071564-3d3221c9-de0d-49ae-a524-e648b75251eb.png)
![image](https://user-images.githubusercontent.com/53989046/185071716-ca1a3d8a-d52f-478b-83da-14b8f9617760.png)

I guess that To filed without port, but Request-Line with port.

**Comment by sgodin** [comment]
Yes, the location server uses the request line for lookups and with the port on the request-uri, you are not matching the registered AOR.  repro is pretty strict about this.  The only time you get away with a port mismatch is if you are using the default SIP port (5060 for UDP/TCP, 5061 for TLS/DTLS) and the user registered without a port.
