### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Lastique** [resiprocate/resiprocate#260]
The latest 1.12.0 release was on May 2020, which is more than 2 years ago at this point. Any new release planned?

Thanks.

PS: It would be nice to have regular releases in general.

**Comment by sgodin** [comment]
This is a discussion, not an issue.  :)

There is already an open discussion for this item:
https://github.com/resiprocate/resiprocate/discussions/232
It is still waiting for feedback from @dpocock
