### ISSUE TITLE
Prevent malicious SIP message

### ISSUE THREAD

**Issue by portsip** [resiprocate/resiprocate#311]
Hi, We have noticed that some SIP attack tools send malicious messages that cause repro to crash. Below is an INVITE message with malicious Contact and From headers. We can receive this message in repro, and when we try to access the host part of the From header, resip throws an exception in ParseBuff::fail. While we can catch this exception, but it would be better if the stack could reject or drop messages containing such headers.

```

Via: SIP/2.0/UDP 45.93.16.168:61959;branch=z9hG4bK478877155

Max-Forwards: 70

Contact: <sip:>;sip:;1001@45.93.16.168:61959

To: <sip:02985750122@116.204.79.16>

From: <sip:>;sip:;1001@116.204.79.16;tag=195413589

Call-ID: 155316273-1827130535-1952322748

CSeq: 1 INVITE

Allow: ACK, BYE, CANCEL, INFO, INVITE, MESSAGE, NOTIFY, OPTIONS, PRACK, REFER, REGISTER, SUBSCRIBE, UPDATE, PUBLISH

Content-Type: application/sdp

User-Agent: Linksys-SPA942

Content-Length: 209



v=0

o=;1001 16264 18299 IN IP4 192.168.1.83

s=call

c=IN IP4 192.168.1.83

t=0 0

m=audio 25282 RTP/AVP 0 101

a=rtpmap:0 pcmu/8000

a=rtpmap:8 pcma/8000

a=rtpmap:101 telephone-event/8000

```

**Comment by sgodin** [comment]
You could try enabling the PEDANTIC_STACK preprocessor flag.  This will cause the stack to try to parse all headers, and handle any issues in TransactionState.  See TransactionState line 580.

Scott
