### ISSUE TITLE
Drop 'GREY' mark on whitelisting? 

### ISSUE THREAD

**Issue by demmax** [resiprocate/resiprocate#319]
Hi! 

I faced with a following issue and hoped you can help:
One of the service providers I use, under some conditions, may ignore my PRACKs (not responding to them), and that leads to marking tuple as `GREY` in TupleMarkManager. 
Finally, it sends back 200 OK (to the initial INVITE) and I need to send ACK. And since the tuple is `GREY`, `DnsResult::lookupInternal()` chooses a TCP transport, which is not supported by the provider. 

So the question is: shouldn't `DnsResult::WhitelistCommand::execute()` unmark the tuple? Or is there any other way to force using only UDP for a specific dialog?

Thank you!

**Comment by sgodin** [comment]
When an entry is grey or black listed it is removed from the VIP/whitelist.  I like the idea of removing at least a greylisted entry if whitelist is called.  However, I think the original author must have considered this and decided not to do it for some reason - I just don't know the reason... perhaps there isn't a good reason.  :)

Assuming you are using DUM, the outboundproxy UserProfile setting can be used to restrict where messages go for a particular INVITE dialog.  If you add ;transport=udp to the outbound proxy uri, then you will lock it to UDP transports only.

**Comment by sgodin** [comment]
@demmax I have modified the code as a trial.  Message me at  sgodin@sipspectrum.com if you want to try it out.

**Comment by sgodin** [comment]
I have checked a change into GIT for this.  Whitelisting now causes a removal from the greylist (regardless of whether DNS VIP feature is enabled or not).  Thanks for testing out the solution @demmax
