### ISSUE TITLE
GCC Sanitize address build crash on Date field of length 16

### ISSUE THREAD

**Issue by searlers** [resiprocate/resiprocate#340]
Culprit appears to be this in Rutils/Data.hxx
```
      char mPreBuffer[LocalAlloc];
      **// Null terminator for mPreBuffer when mSize==LocalAlloc lands here; this
      // is ok, because Borrow==0.**
      // Note: we could use a char here, and expand mPreBuffer by 3 bytes, but 
      // this imposes a performance penalty since it requires operating on a 
      // memory location smaller than a word (requires masking and such).
      size_type mShareEnum;
```
If the address sanitizer is enabled, there is a crash on any memory issue (because it is hard to continue running when the memory is considered to be corrupted).
Is this performance consideration really critical?

**Comment by sgodin** [comment]
I'd like to understand why it's crashing better.  Do you have a unit test that duplicates the crash?

**Comment by searlers** [comment]
Sorry, I wasn't quite as clear as I thought.
We are compiling our application (including Resiprocate) with g++ with the
address sanitizer flag enabled for test runs - this is a lot better than
Valgrind because it has lower overhead and allows us greater coverage of
temporal interactions and load effects.

If the address sanitizer detects an out of bounds write, it immediately
terminates the program at that point because it doesn't make sense to
continue running with possibly corrupt memory.
I wanted to understand the trade-offs around that optimization so that we
can get further through the test run and actually detect problems in our
code or use of Resiprocate without
the process terminating in the first few seconds of operation.

There isn't a crash and I agree that the code in question is 'clever' and
has no side-effects operationally, provided the assertion about mShareEnum
= 0 (Borrow) is true and that seems to be the case.
Unfortunately, with automated memory usage validation tools, they can't
tell the difference between a 'safe' unsafe write and an unsafe write and
that causes problems with our test regime.
We can easily work-around this locally but it would be helpful to know if
there is any performance analysis or strong justification for the unsafe
use of the buffer

Thanks

**Comment by sgodin** [comment]
Thank you for the more detailed explanation!  In general I'm always for an optimization, but this appears to be a bit of dangerous one.  I'd be game to accept a PR here.  I could be wrong here, but it seems the best solution would be to just change the line to be:
char mPreBuffer[LocalAlloc+1];
The current comments about expanding by 3 bytes only makes sense on 32-bit architectures, most systems are 64 bit now.  I suppose if we modified LocalAlloc to 15, we'd end up with a mPreBuffer of 16 chars = 128 bits... a good size for both architectures.  On the negative side, any data of size 16 will now require a new allocation.

Thoughts?

**Comment by searlers** [comment]
We will come up with a local fix and pass it to you for review. I don't think the penalty of explicitly limiting the bounds will be significant but we will investigate the options
