### ISSUE TITLE
Deadlock hazard

### ISSUE THREAD

**Issue by FoZu19940620** [resiprocate/resiprocate#347]
I'm a fan of this project，I've been watching it. I find that such an implementation can be a burden on callers. Because the caller cannot add another lock to the handler callback, Otherwise, deadlock exists. This is the code in the project.

TurnAsyncSocket::disableTurnAsyncHandler()
{
   RecursiveLock lock(mHandlerMutex);
   mTurnAsyncSocketHandler = 0;
}

Maybe you can solve it this way.The pseudo-code is as follows.
TurnAsyncSocket::disableTurnAsyncHandler()
{
    std::condition_variable cv;
    std::mutex mtx;
    bool flag = false;

    mIOService.dispatch([&] {
        mtx.lock();
        flag = true;
        mtx.unlock();
        cv.notify_one();
    });

    std::unique_lock<std::mutex> lck(mtx);
    cv.wait(lck, [&] {return flag; });//If the caller calls is in mIOService thread, it won't block.
}
This way all callbacks don't have to be callback in the lock. Just need flag == true callback
I like your project, I really hope this project will get better and better.

**Comment by FoZu19940620** [comment]
Maybe it should be.

mIOService.dispatch([&] {
    mtx.lock();
    flag = true;
    mtx.unlock();
    cv.notify_one();
}));

std::unique_lock<std::mutex> lck(mtx);
cv.wait(lck,[]{return flag;});

**Comment by FoZu19940620** [comment]
If you think my suggestion is not a good idea, I hope you can tell me why, thank you.

**Comment by sgodin** [comment]
To be honest I don't fully understand what the problem is or what your
solution is doing to solve it.  Why is adding an application lock causing a
deadlock?  What is "flag" in your proposed solutions?  Is that supposed to
be mTurnAsyncSocketHandler?  Without being able to quickly understand the
problem and or solution it's difficult for anyone to give feedback.   Thank
you for your appreciation of the project.  :)

Scott

**Comment by FoZu19940620** [comment]
The lower layer usually does not hold internal lock callbacks, because if the upper layer thread holds the upper layer lock and calls the underlying interface, there is a deadlock. The above method can be callback without holding an internal lock, Direct callback.
