### ISSUE TITLE
There is a memory leak in the makePagerMessage method.

### ISSUE THREAD

**Issue by mc373906408** [resiprocate/resiprocate#363]
Hello, this project is great, I compiled it as a library to import into my project.
I was dismayed to find that I had a slight memory leak when using makePagerMessage mode. The leak reached 100MB in 12 hours. Here is my code

        uri.host() = resip::Data(ip.c_str());
        uri.port() = port;
        resip::NameAddr destAddr(uri);
        std::unique_lock<std::mutex> lock(_dumMtx);
        resip::ClientPagerMessageHandle msgHandle = _dum->makePagerMessage(destAddr);

        static resip::Mime typeXML("Application", "MANSCDP+xml");
        std::unique_ptr<resip::Contents> content(std::make_unique<resip::PlainContents>(data, typeXML));
        resip::SipMessage &msg = msgHandle->getMessageRequest();
        callId = msg.header(h_CallID).value().c_str();

        std::string duriStr = bio::BioTools::str_format("sip:%s@%s:%d", user.c_str(), ip.c_str(), port);
        if (transport == RedisTool::UDP) {
            duriStr += ";transport=udp";
        } else if (transport == RedisTool::TCP) {
            duriStr += ";transport=tcp";
        } else if (transport == RedisTool::TLS) {
            duriStr += ";transport=tls";
        }
        resip::Uri duri(duriStr.c_str());
        msg.setForceTarget(duri);
        msgHandle->page(std::move(content));

**Comment by mc373906408** [comment]
I checked the heap memory and found a large number of new void instances created by StlPoolAllocator::allocate_raw

**Comment by sgodin** [comment]
You are not ending the ClientPagerMessage dialogset, via the ClientPagerMessage handler.  ClientPagerMessage is meant to be created once and you can send multiple messages to the destination with it.  When you are done using it, you need to end() it.

Have you explored using a ClientPagerMessageHandler to get feed on whether the page command was successful or not?  See basicMessage.cxx in resip/dum/test for an example.  Unfortunately this example doesn't call the end call - so ignore that bit.  If you are just sending a single message.  You could be calling ClientPagerMessageHandle->end() in the onSuccess and onFailure callbacks.  If you call it before a response is received, then the callbacks won't occur and any queued up messages will be discarded.

**Comment by mc373906408** [comment]
Thank you, this problem was solved perfectly.

I would also like to know if "makeOutOfDialogRequest" and "makeInviteSession" also need to be active end

**Comment by sgodin** [comment]
InviteSessions must be ended, not sure about OutOfDialogRequests offhand.  If you look at the source code it should help,  look for and end() method.
