### ISSUE TITLE
Are there plans to support watchOS?

### ISSUE THREAD

**Issue by Echo2087** [resiprocate/resiprocate#372]
Are there plans to support watchOS?
Starting from watchOS9, Apple Watch supports the use of CallKit, making it possible to build SIP software on Apple Watch, but establishing a network connection on watchOS can only use the API provided by Apple

**Comment by sgodin** [comment]
I'm not aware of anyone with plans, but would encourage others to speak up if they are thinking of tackling this.  If you are interesting in funding such an endeavor then send me a DM.
