### ISSUE TITLE
“WebRTC-and-SIP-Over-WebSockets” Is the wiki obsolete?

### ISSUE THREAD

**Issue by mc373906408** [resiprocate/resiprocate#376]
[https://github.com/resiprocate/resiprocate/wiki/WebRTC-and-SIP-Over-WebSockets](url)

This configuration has been deleted
`AssumePath = true`

Do I need to configure the following two parameters？
`
DisableOutbound = false
EnableFlowTokens = true
`

Do I have the same effect if I configure it like this instead of using the config file?
`
InteropHelper::setOutboundSupported(true);
InteropHelper::setRRTokenHackEnabled(true);
`

**Comment by sgodin** [comment]
AssumePath option was removed a while ago, I will edit the wiki page and remove it.

Yes you need those parameters, and setting the options in code is fine too.
