### ISSUE TITLE
How to add a custom header to a SIP response of UAS?

### ISSUE THREAD

**Issue by elevenxia** [resiprocate/resiprocate#390]
As a UAS, when receiving a SIP INVITE request, the member function of the class InviteSessionHandler is called:
void onNewSession(ServerInviteSessionHandle, InviteSession::OfferAnswerType oat, const SipMessage& msg)
Afterward, the ServerInviteSession::accept function is invoked to send a 200 OK response to the initial INVITE. From the source code, it appears that the headers of the response are generated from the headers of the request. My question is, how can I add a custom header to the response before calling the ServerInviteSession::accept function? For instance, how can I add a Subject header to the response?
Thanks.

**Comment by sgodin** [comment]
Check out this wiki page: https://github.com/resiprocate/resiprocate/wiki/Modifying-Decorating-messages-sent

**Comment by sgodin** [comment]
On another note:  In general, please post questions to the Discussions board, and use the Issues bord for bugs/defects.  Thank you!

**Comment by elevenxia** [comment]
@sgodin Thank you so much! This has been very helpful to me.
